# Generated by Django 5.2.7 on 2025-11-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='associated_group',
            field=models.CharField(choices=[('A', 'GroupA'), ('B', 'GroupB'), ('N', 'None')], default='N', max_length=1, verbose_name='関連付けグループ'),
        ),
    ]
