# Generated by Django 5.2.7 on 2025-11-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group_a_name',
            field=models.CharField(default='Group A', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group_b_name',
            field=models.CharField(default='Group B', max_length=50),
        ),
    ]
